### ISSUE TITLE
sfx not seeing uploads

### ISSUE THREAD

**Issue by roormonger** [baiumbg/useless-cogs#12]
Hello. Thank you so much for porting this to V3. The problem I am having is that when I upload an audio clip, I get an error saying "Error in command 'addsfx'. Check your console logs for details". The console will say something about the file not being found. The clip does get uploaded but if I try to play it the cog will say it doesnt exist. If I try the "allsfx" command it will tell me there are no files.

Thank you for your time.

**Comment by baiumbg** [comment]
Hey there. Can you post the error from the logs during upload? And which version of Red are you using?

**Comment by roormonger** [comment]
I am using Red v3.1.6. Here is the log when I upload.

[2019-10-20 12:18:33] [ERROR] red: Exception in command 'addsfx'
Traceback (most recent call last):
  File "c:\python 38\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\apps\botbuffer\cogs\CogManager\cogs\sfx\sfx.py", line 214, in addsfx
    audio_data = pydub.AudioSegment.from_file(filepath, format=file_extension[1:])
  File "C:\apps\botbuffer\cogs\Downloader\lib\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\apps\botbuffer\cogs\Downloader\lib\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\python 38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python 38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


Also when the cog is loaded and I start the bot up I get an error about ffmpeg not being installed.

C:\apps\botbuffer\cogs\Downloader\lib\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by baiumbg** [comment]
Can you try installing ffmpeg? It's needed, because the bot has to add padding to every sound you upload to circumvent a limitation in the audio player of Red. Might need to add that info somewhere :P

Uploading works fine for me.

**Comment by roormonger** [comment]
Where is it looking for it? As in where to I put it.

**Comment by baiumbg** [comment]
Anywhere that's in your OS' search path. Look here: https://github.com/jiaaro/pydub#getting-ffmpeg-set-up

**Comment by roormonger** [comment]
Adding ffmpeg to PATH worked. Thank you.

On a side note do you plan on adding the feature the cog used to have where if you typed part of a name it would randomly play a clip that started with those letters?

**Comment by baiumbg** [comment]
I had no idea the original cog had that functionality. I'll probably add it at some point in the future, but I don't really have time to work on my cogs at the moment.
PRs are welcome, though 😛
